resources:
- repo: self
  fetchDepth: 1
pool:
  vmImage: 'ubuntu-latest'
trigger:
- master
variables:
  TargetFramework: 'netcoreapp3.1'
  BuildConfiguration: 'Release'
  DockerImageName: 'mlops1-349012/clouddemo'
steps:
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
- task: Docker@2
  displayName: 'Login to Container Registry'
  inputs:
    command: login
    containerRegistry: 'gcr-tutorial'
- task: Docker@2
  displayName: 'Build and push image'
  inputs:
    Dockerfile: 'Dockerfile'
    command: buildAndPush
    repository: '$(DockerImageName)'